---
steps:
  - name: gcr.io/kaniko-project/executor:latest
    id: sumservice-docker
    waitFor:
      - "-"
    args:
      - --cache=true
      - --cache-ttl=168h
      - --destination=${_REGION}-docker.pkg.dev/${PROJECT_ID}/registry/sumservice:${COMMIT_SHA}
      - --dockerfile=sumservice/Dockerfile
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    id: sumservice-deploy
    waitFor:
      - sumservice-docker
    entrypoint: gcloud
    args:
      - run
      - deploy
      - sumservice
      - --execution-environment=gen2
      - --image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/registry/sumservice:${COMMIT_SHA}
      - --region=${_REGION}
substitutions:
  _REGION: us-central1
